name: trigger server to update cached data
on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │  ┌───────────── day of the month (1 - 31)
    #        │ │  │  ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │  │  │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │  │  │ │
    #        │ │  │  │ │
    #        │ │  │  │ │
    #        * *  *  * *
    - cron: "45 /12 * * *"
  workflow_dispatch:

jobs:
  triggerRepeatRecent:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://github-readme-stats-git-caching-martin-mfgs-projects.vercel.app/api/repeat-recent"
          method: "POST"
          timeout: "62000"
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.status }}
